service: taskApi
frameworkVersion: "3"

# AWS ->
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  memorySize: 128
  logRetentionInDays: 1
  environment:
    TASKS_TABLE_NAME: !Ref TaskTable
    REGION: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

# Api Serverless -> get, create, update
functions:
  getTask:
    handler: src/handlers/getTask.handler
    events:
      - httpApi:
          path: /task
          method: get
  createTask:
    handler: src/handlers/createTask.handler
    events:
      - httpApi:
          path: /task
          method: post
  updateTask:
    handler: src/handlers/updateTask.handler
    events:
      - httpApi:
          path: /task/{id}
          method: put

# DynamoDB, Cognito ->
resources:
  Resources:
    TasksTable: ${file(resources/TaskTable.yml):TaskTable}
#
