service: taskApi
frameworkVersion: "3"

# AWS, IAM, ENV ->
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  memorySize: 128
  logRetentionInDays: 1
  environment:
    TASKS_TABLE_NAME: !Ref TaskTable
    REGION: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    httpApi:
    authorizers:
      tokenAuth:
        type: request
        identitySource:
          - $request.header.Authorization
        functionName: tokenAuthorizer

# Api Serverless -> get, create, update
functions:
  # auth
  tokenAuthorizer:
    handler: src/auth/tokenAuthorizer.js
  getTask:
    handler: src/handlers/getTask.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Scan
        Resource: !GetAtt TaskTable.Arn
    events:
      - httpApi:
          path: /task
          method: get
          authorizer: tokenAuth
  createTask:
    handler: src/handlers/createTask.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt TaskTable.Arn
    events:
      - httpApi:
          path: /task
          method: post
          authorizer: tokenAuth
  updateTask:
    handler: src/handlers/updateTask.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt TaskTable.Arn
    events:
      - httpApi:
          path: /task/{id}
          method: put
          authorizer: tokenAuth
  #
  plugins:
    - serverless-iam-roles-per-function
    - serverless-plugin-include-dependencies

# DynamoDB, Cognito ->
resources:
  Resources:
    TasksTable: ${file(resources/TaskTable.yml):TaskTable}
#

plugins:
  - serverless-iam-roles-per-function
