service: taskApi
frameworkVersion: "3"

# AWS, IAM, ENV->
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  memorySize: 128
  logRetentionInDays: 1
  environment:
    TASKS_TABLE_NAME: !Ref TaskTable
    REGION: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

# Api Serverless -> get, create, update
functions:
  getTask:
    handler: src/handlers/getTask.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Scan
        Resource: !GetAtt TaskTable.Arn
    events:
      - httpApi:
          path: /task
          method: get
  createTask:
    handler: src/handlers/createTask.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt TaskTable.Arn
    events:
      - httpApi:
          path: /task
          method: post
  updateTask:
    handler: src/handlers/updateTask.handler
    events:
      - httpApi:
          path: /task/{id}
          method: put
  #
  plugins:
    - serverless-iam-roles-per-function
    - serverless-plugin-include-dependencies

# DynamoDB, Cognito ->
resources:
  Resources:
    TasksTable: ${file(resources/TaskTable.yml):TaskTable}
#

plugins:
  - serverless-iam-roles-per-function
